[package]
name = "cpu"
version = "1.0.0"
authors = []

[addresses]
cpu_addr = "5419a96dc733723049e6a2ea8405c474e925b9eeb6aa1a89ff48eff2cd5d686d"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies]
libs = { git = "https://github.com/hduoc2003/navori-libs", rev = "main" }