[package]
name = "cpu"
version = "1.0.0"
authors = []

[addresses]
cpu_addr = "0xad09869b94e545ee882dd1783cc122dd5a7527e6339065a6070507f8beed4f8b"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies]
libs = { git = "https://github.com/hduoc2003/navori-libs", rev = "main" }
