[package]
name = "cpu"
version = "1.0.0"
authors = []

[addresses]
cpu_addr = "8f570bc93bd5ebe528ed5750e51361fd282f382cc0dbf975486183a83c80e8cc"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies]
libs = { git = "https://github.com/hduoc2003/navori-libs", rev = "main" }
