[package]
name = "cpu"
version = "1.0.0"
authors = []

[addresses]
cpu_addr = "04b410848f9f4af865a879ef9fbafa43e0696c197646c05d1ae4d6aa89c512fd"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies]
libs = { git = "https://github.com/hduoc2003/navori-libs", rev = "main" }