[package]
name = "cpu"
version = "1.0.0"
authors = []

[addresses]
cpu_addr = "0xc4c2c4bd21144492b6d8b81588879d58ed9796cc3a1556274879472bbb3fa462"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies]
libs = { git = "https://github.com/hduoc2003/navori-libs", rev = "main" }