[package]
name = "cpu"
version = "1.0.0"
authors = []

[addresses]
cpu_addr = "2e5da516cf8fe50505f46a661fced1fc92b263b47dd594a2e535f5db174913e3"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies]
libs = { git = "https://github.com/hduoc2003/navori-libs", rev = "main" }
